/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamentohospitalar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author icuro
 */
public class AgendarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form AgendarConsulta
     */
    public AgendarConsulta() {
        super("Agendamento de consultas");
        initComponents();
        this.setLocationRelativeTo(null);
                
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataTextField = new javax.swing.JTextField();
        confirmarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        especialidadeTextField = new javax.swing.JTextField();
        hospitalTextField = new javax.swing.JTextField();
        pacienteTextField = new javax.swing.JTextField();
        medicoTextField = new javax.swing.JTextField();
        convenioTextField = new javax.swing.JTextField();
        planoDeSaudeTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        paciente = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        hospital = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        medico = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        convenio = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        planosaude = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        planosaude1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dataTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite a data e hora da consulta:"));
        dataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTextFieldActionPerformed(evt);
            }
        });

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        especialidadeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID da especialidade do médico:"));
        especialidadeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadeTextFieldActionPerformed(evt);
            }
        });

        hospitalTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID do hospital:"));

        pacienteTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID do paciente:"));
        pacienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pacienteTextFieldActionPerformed(evt);
            }
        });

        medicoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID do médico:"));
        medicoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicoTextFieldActionPerformed(evt);
            }
        });

        convenioTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID do convênio:"));
        convenioTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convenioTextFieldActionPerformed(evt);
            }
        });

        planoDeSaudeTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Digite o ID do plano de saúde:"));
        planoDeSaudeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planoDeSaudeTextFieldActionPerformed(evt);
            }
        });

        paciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "              Ícaro"},
                {"                   2", "              Andrey"},
                {"                   3", "              César"}
            },
            new String [] {
                "ID", "Paciente"
            }
        ));
        jScrollPane2.setViewportView(paciente);

        hospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "              Diadema"},
                {"                   2", "              Santa Casa"},
                {"                   3", "              Municipal"}
            },
            new String [] {
                "ID", "Hospital"
            }
        ));
        jScrollPane4.setViewportView(hospital);

        medico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "              Tulio"},
                {"                   2", "              Fábio"},
                {"                   3", "            Fernando"}
            },
            new String [] {
                "ID", "Médico"
            }
        ));
        jScrollPane5.setViewportView(medico);

        convenio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "               SUS"},
                {"                   2", "             Bradesco Saúde"},
                {"                   3", "             Unimed"}
            },
            new String [] {
                "ID", "Convênio"
            }
        ));
        jScrollPane6.setViewportView(convenio);

        planosaude.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "               Atendimento Público"},
                {"                   2", "             Premium"},
                {"                   3", "             Fama"}
            },
            new String [] {
                "ID", "Plano de Saúde"
            }
        ));
        jScrollPane7.setViewportView(planosaude);

        planosaude1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"                   1", "             Ortopedista"},
                {"                   2", "             Clínico Geral"},
                {"                   3", "             Neurologista"}
            },
            new String [] {
                "ID", "Especialidade"
            }
        ));
        jScrollPane8.setViewportView(planosaude1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(hospitalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(168, 168, 168)
                        .addComponent(pacienteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(convenioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160)
                        .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(planoDeSaudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(83, 83, 83)
                            .addComponent(especialidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hospitalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(pacienteTextField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(convenioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(planoDeSaudeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    .addComponent(especialidadeTextField))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
     
        String data_hora = dataTextField.getText();
     int paciente = Integer.parseInt(pacienteTextField.getText());
     int hospital = Integer.parseInt(hospitalTextField.getText()); 
     int medico = Integer.parseInt(medicoTextField.getText());
     int especialidade = Integer.parseInt(especialidadeTextField.getText());
     int convenio = Integer.parseInt(convenioTextField.getText());
     int plano_saude = Integer.parseInt(planoDeSaudeTextField.getText());
     try{
         Consulta consulta = new Consulta(0, data_hora, paciente, hospital, medico, especialidade, convenio, plano_saude);
      AgendamentoDAO dao = new AgendamentoDAO();
        dao.agendar(consulta);  
        JOptionPane.showMessageDialog(null, "Consulta agendada com sucesso!");
        
     } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Não foi possível agendar a consulta.");
     }
        
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        CRUDTela t = new CRUDTela();
        t.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void convenioTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convenioTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_convenioTextFieldActionPerformed

    private void especialidadeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especialidadeTextFieldActionPerformed

    private void dataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataTextFieldActionPerformed

    private void planoDeSaudeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planoDeSaudeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planoDeSaudeTextFieldActionPerformed

    private void medicoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicoTextFieldActionPerformed

    private void pacienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pacienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pacienteTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarButton;
    private javax.swing.JTable convenio;
    private javax.swing.JTextField convenioTextField;
    private javax.swing.JTextField dataTextField;
    private javax.swing.JTextField especialidadeTextField;
    private javax.swing.JTable hospital;
    private javax.swing.JTextField hospitalTextField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable medico;
    private javax.swing.JTextField medicoTextField;
    private javax.swing.JTable paciente;
    private javax.swing.JTextField pacienteTextField;
    private javax.swing.JTextField planoDeSaudeTextField;
    private javax.swing.JTable planosaude;
    private javax.swing.JTable planosaude1;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
