/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.agendamentohospitalar;

import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class CRUDTela extends javax.swing.JFrame {

    public CRUDTela() {
        super("Gerenciador de consultas");
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            AgendarConsulta();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível estabelecer conexão.");
        }
    }
    
    private void AgendarConsulta() throws Exception {
        DefaultTableModel model = (DefaultTableModel) tableOpcoes.getModel();
        model.setRowCount(0);

        String sql = "SELECT ag.id, data_hora, hos.nome_hospital AS HOSPITAL, pac.nome AS NOME_PACIENTE, med.nome_medico AS NOME_MEDICO, con.nome_convenio AS CONVENIO, plan.plano_de_saude AS PLANO, esp.nome_especialidade AS ESPECIALIDADE\n" +
"FROM agendamento ag\n" +
"JOIN medico med ON ag.id_medico = med.id\n" +
"JOIN paciente pac ON ag.id_paciente = pac.id\n" +
"JOIN hospital hos ON ag.id_hospital = hos.id\n" +
"JOIN convenio con ON ag.id_convenio = con.id\n" +
"JOIN plano_saude plan ON ag.id_plano_de_saude = plan.id\n" +
"JOIN especialidade esp ON ag.id_especialidade = esp.id;";

        try (Connection conn = ConexaoBD.obtemConexao(); PreparedStatement ps = conn.prepareStatement(sql)) {
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3),
                    rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8)});

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        atualizarConsultaButton = new javax.swing.JButton();
        agendarConsultaButton = new javax.swing.JButton();
        excluirConsultaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOpcoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de Consultas"));

        atualizarConsultaButton.setText("Atualizar");
        atualizarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarConsultaButtonActionPerformed(evt);
            }
        });

        agendarConsultaButton.setText("Agendar");
        agendarConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendarConsultaButtonActionPerformed(evt);
            }
        });

        excluirConsultaButton.setText("Excluir");
        excluirConsultaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirConsultaButtonActionPerformed(evt);
            }
        });

        tableOpcoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data/Hora", "Hospital", "Paciente", "Médico", "Convênio", "Plano de Saúde", "Especialidade"
            }
        ));
        jScrollPane2.setViewportView(tableOpcoes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(agendarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(306, 306, 306)
                        .addComponent(excluirConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                        .addComponent(atualizarConsultaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(atualizarConsultaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(excluirConsultaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agendarConsultaButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarConsultaButtonActionPerformed
AtualizarConsulta ac = new AtualizarConsulta();
        ac.setVisible(true);
    }//GEN-LAST:event_atualizarConsultaButtonActionPerformed

    private void agendarConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendarConsultaButtonActionPerformed
        AgendarConsulta a = new AgendarConsulta();
        a.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_agendarConsultaButtonActionPerformed

    private void excluirConsultaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirConsultaButtonActionPerformed

        ExcluirAgendamento a = new ExcluirAgendamento();
        a.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_excluirConsultaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agendarConsultaButton;
    private javax.swing.JButton atualizarConsultaButton;
    private javax.swing.JButton excluirConsultaButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableOpcoes;
    // End of variables declaration//GEN-END:variables


}
